--create table Loan_App_Master (
--	Loan_App_Id VARCHAR(50),
--	Application_Date DATE,
--	Interest_Rate DECIMAL(4,2)
--);
--
--create table Loan_App_Detail_Master (
--        Id varchar(255) not null,
--        Installment integer,
--        Interest_Rate float(24),
--        Last_Date_Of_Install_Pay date,
--        Month_No integer,
--        P_Outstanding_Begin_Of_Mon integer,
--        P_Repayment integer,
--        P_Outstanding_End_Of_Mon integer,
--        Loan_App_Master_Loan_App_Id varchar(6),
--       	Last_Date_Of_Install_Pay date,
--        primary key (id),
--        foreign key (Loan_App_Master_Loan_App_Id) references Loan_App_Master(Loan_App_Id)
--    )
--    
--create table Loan_Master (
--        Loan_Id varchar(255) not null,
--        Date_Of_Creation date,
--        Interest_Rate float(24),
--        Type_Of_Loan varchar(255) check (Type_Of_Loan in ('PERSONAL_LOANS','AUTO_LOANS','BUSINESS_LOANS','HOME_LOANS')),
--        primary key (Loan_Id)
--    )